// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace DurableTask.SqlServer
{
    using System.Diagnostics;
    using System.Text;
    using DurableTask.Core;
    using DurableTask.Core.History;
    using SemVersion;

    static class DTUtils
    {
        public static readonly SemanticVersion ExtensionVersion = GetExtensionVersion();
        public static readonly string ExtensionVersionString = GetExtensionVersionForLogging(ExtensionVersion);

        // DurableTask.Core has a public static variable that contains the app name
        public static readonly string AppName = DurableTask.Core.Common.Utils.AppName;

        static SemanticVersion GetExtensionVersion()
        {
            // The product version is auto-generated by the Microsoft.SourceLink.GitHub nuget package.
            // Example: 0.1.0-alpha+46661b102c4ccd123f46782f481c3d4b004e3845
            string productVersion = FileVersionInfo.GetVersionInfo(
                typeof(SqlOrchestrationService).Assembly.Location).ProductVersion;
            return SemanticVersion.Parse(productVersion);
        }

        static string GetExtensionVersionForLogging(SemanticVersion version)
        {
            var builder = new StringBuilder();
            builder
                .Append(version.Major)
                .Append('.')
                .Append(version.Minor)
                .Append('.')
                .Append(version.Patch);

            if (!string.IsNullOrEmpty(version.Prerelease))
            {
                builder.Append('-').Append(version.Prerelease);
            }
#if DEBUG
            // Include the build information only in debug builds
            if (!string.IsNullOrEmpty(version.Build))
            {
                builder.Append('+').Append(version.Build);
            }
#endif
            return builder.ToString();
        }

        public static int GetTaskEventId(HistoryEvent historyEvent)
        {
            if (TryGetTaskScheduledId(historyEvent, out int taskScheduledId))
            {
                return taskScheduledId;
            }

            return historyEvent.EventId;
        }

        static bool TryGetTaskScheduledId(HistoryEvent historyEvent, out int taskScheduledId)
        {
            switch (historyEvent.EventType)
            {
                case EventType.TaskCompleted:
                    taskScheduledId = ((TaskCompletedEvent)historyEvent).TaskScheduledId;
                    return true;
                case EventType.TaskFailed:
                    taskScheduledId = ((TaskFailedEvent)historyEvent).TaskScheduledId;
                    return true;
                case EventType.SubOrchestrationInstanceCompleted:
                    taskScheduledId = ((SubOrchestrationInstanceCompletedEvent)historyEvent).TaskScheduledId;
                    return true;
                case EventType.SubOrchestrationInstanceFailed:
                    taskScheduledId = ((SubOrchestrationInstanceFailedEvent)historyEvent).TaskScheduledId;
                    return true;
                case EventType.TimerFired:
                    taskScheduledId = ((TimerFiredEvent)historyEvent).TimerId;
                    return true;
                case EventType.ExecutionStarted:
                    var parentInstance = ((ExecutionStartedEvent)historyEvent).ParentInstance;
                    if (parentInstance != null)
                    {
                        // taskId that scheduled a sub-orchestration
                        taskScheduledId = parentInstance.TaskScheduleId;
                        return true;
                    }
                    else {
                        taskScheduledId = -1;
                        return false;
                    }
                default:
                    taskScheduledId = -1;
                    return false;
            }
        }

        public static int GetPayloadSizeInBytes(TaskMessage message)
        {
            if (TryGetPayloadText(message.Event, out string? payloadText) && payloadText != null)
            {
                return Encoding.UTF8.GetByteCount(payloadText);
            }

            return -1;
        }

        public static bool TryGetPayloadText(HistoryEvent e, out string? payloadText)
        {
            payloadText = e.EventType switch
            {
                EventType.ContinueAsNew => ((ContinueAsNewEvent)e).Result,
                EventType.EventRaised => ((EventRaisedEvent)e).Input,
                EventType.EventSent => ((EventSentEvent)e).Input,
                EventType.ExecutionCompleted => ((ExecutionCompletedEvent)e).Result,
                EventType.ExecutionFailed => ((ExecutionCompletedEvent)e).Result,
                EventType.ExecutionStarted => ((ExecutionStartedEvent)e).Input,
                EventType.ExecutionTerminated => ((ExecutionTerminatedEvent)e).Input,
                EventType.GenericEvent => ((GenericEvent)e).Data,
                EventType.SubOrchestrationInstanceCompleted => ((SubOrchestrationInstanceCompletedEvent)e).Result,
                EventType.SubOrchestrationInstanceCreated => ((SubOrchestrationInstanceCreatedEvent)e).Input,
                EventType.SubOrchestrationInstanceFailed => ((SubOrchestrationInstanceFailedEvent)e).Details,
                EventType.TaskCompleted => ((TaskCompletedEvent)e).Result,
                EventType.TaskFailed => ((TaskFailedEvent)e).Details,
                EventType.TaskScheduled => ((TaskScheduledEvent)e).Input,
                _ => null,
            };

            return payloadText != null;
        }

        public static bool HasPayload(HistoryEvent e)
        {
            return TryGetPayloadText(e, out string? text) && !string.IsNullOrEmpty(text);
        }

        public static string? GetName(HistoryEvent historyEvent)
        {
            return historyEvent.EventType switch
            {
                EventType.EventRaised => ((EventRaisedEvent)historyEvent).Name,
                EventType.EventSent => ((EventSentEvent)historyEvent).Name,
                EventType.ExecutionStarted => ((ExecutionStartedEvent)historyEvent).Name,
                EventType.SubOrchestrationInstanceCreated => ((SubOrchestrationInstanceCreatedEvent)historyEvent).Name,
                EventType.TaskScheduled => ((TaskScheduledEvent)historyEvent).Name,
                _ => null,
            };
        }

        public static OrchestrationStatus? GetRuntimeStatus(HistoryEvent historyEvent)
        {
            switch (historyEvent.EventType)
            {
                case EventType.ExecutionCompleted:
                case EventType.ExecutionFailed:
                    return ((ExecutionCompletedEvent)historyEvent).OrchestrationStatus;
                default:
                    return null;
            }
        }

        public static string? GetParentInstanceId(HistoryEvent historyEvent)
        {
            return historyEvent.EventType switch
            {
                EventType.ExecutionStarted => ((ExecutionStartedEvent)historyEvent).ParentInstance?.OrchestrationInstance.InstanceId,
                _ => null,
            };
        }

        public static string? GetVersion(HistoryEvent historyEvent)
        {
            return historyEvent.EventType switch
            {
                EventType.ExecutionStarted => ((ExecutionStartedEvent)historyEvent).Version,
                EventType.TaskScheduled => ((TaskScheduledEvent)historyEvent).Version,
                _ => null,
            };
        }
    }
}
