name: Publish Release

on:
  push:
    tags:
      - v* #version is cut

env:
  GITHUB_SOURCE: "https://nuget.pkg.github.com/microsoft/index.json"
  CONFIGURATION: Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          8.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Publish
      run: dotnet nuget push --api-key ${{ secrets.GITHUB_TOKEN }} --source ${{ env.GITHUB_SOURCE }} "**/*.nupkg"
